" ------------ General Config ---------------

set number 			" show line numbers
set rnu				" show relative line numbers
set history=1000		" store lots of :cmdline history
set showcmd			" show incomplete cmds
set autoread			" reload files changed outside vim

" ------------ Indendtent -------------------

set tabstop=4			" show existing tab with 4 space width 
set shiftwidth=4		" when indenting with '>', use 4 spaces width 
set expandtab			" when pressing tab, insert spaces instead
set autoindent          " copy the indentent of current line when start a new line.	
set smartindent         " smart indent, works with C-like languges
set smarttab            




" ------------ Plugin Setting --------------


" Add plugin with Vim-plug
call plug#begin('~/.vim/plugged')

" NERDtree: a tree look directroy plugin
Plug 'scrooloose/nerdtree'

" Airline: bottom status bar
Plug 'vim-airline/vim-airline'
Plug 'vim-airline/vim-airline-themes'

" vim-indent-guides: shows the indents 
Plug 'nathanaelkane/vim-indent-guides'
 
Plug 'scrooloose/syntastic'
Plug 'valloric/youcompleteme'
Plug 'airblade/vim-gitgutter'
Plug 'kien/ctrlp.vim'

Plug 'plasticboy/vim-markdown'

call plug#end()


" for airline theme
set laststatus=2
let g:airline_theme='luna'


" for youcompleteme
let g:ycm_python_binary_path = '/usr/bin/python3'


" ------------- Key Mapping ------------

" jump between splits
nnoremap <C-J> <C-W><C-J> 
nnoremap <C-K> <C-W><C-K>
nnoremap <C-L> <C-W><C-L>
nnoremap <C-H> <C-W><C-H>

" For NERDTree
map <C-n> :NERDTreeToggle<CR>
